### ISSUE TITLE
FreeCAD crashes when trying Addons Manager

### ISSUE THREAD

**Issue by spanakop** [ghostbsd/ghostbsd-src#45]
When I try to use the Addons Manager feature, FreeCAD will crash straight away. Below is the output from the CLI when I am running FreeCAD from it.

I'm running Mate and GhostBSD is the latest stable 12.2 release. 

```
$ FreeCAD
FreeCAD 0.18, Libs: 0.18R0.18.5
© Juergen Riegel, Werner Mayer, Yorik van Havre 2001-2019
  #####                 ####  ###   ####  
  #                    #      # #   #   # 
  #     ##  #### ####  #     #   #  #   # 
  ####  # # #  # #  #  #     #####  #   # 
  #     #   #### ####  #    #     # #   # 
  #     #   #    #     #    #     # #   #  ##  ##  ##
  #     #   #### ####   ### #     # ####   ##  ##  ##

Traceback (most recent call last):
  File "/usr/local/FreeCAD/Mod/AddonManager/AddonManager.py", line 790, in run
    u = urlopen(url)
  File "/usr/local/FreeCAD/Mod/AddonManager/addonmanager_utilities.py", line 36, in urlopen
    u = urllib2.urlopen(url, context=ssl_ctx)
  File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 1393, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/local/lib/python3.7/urllib/request.py", line 1350, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/lib/python3.7/http/client.py", line 1277, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1288, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/local/lib/python3.7/http/client.py", line 1122, in putrequest
    self._validate_path(url)
  File "/usr/local/lib/python3.7/http/client.py", line 1222, in _validate_path
    raise InvalidURL(f"URL can't contain control characters. {url!r} "
http.client.InvalidURL: URL can't contain control characters. '/opensearch.xml" title="GitHub">   <link rel="fluid-icon" href="https:/' (found at least ' ')
Segmentation fault
```

**Comment by ericbsd** [comment]
Is it still hapening?

**Comment by ericbsd** [comment]
On 21.05.01 I was able to install addons without error.

**Comment by spanakop** [comment]
Apologies for the late reply, I have only just installed the latest version. FreeCAD is working correctly now on the latest version of GBSD (GhostBSD-21.05.04.iso)

**Comment by ericbsd** [comment]
issue moved from ghostbsd/ghostbsd-src to ghostbsd/issues
